# Generated by Django 4.1.3 on 2022-11-12 07:27

import basic_services.service
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('private', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, upload_to=basic_services.service.get_path_upload_album, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), basic_services.service.validate_size_image])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Жанр')),
                ('cover', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), basic_services.service.validate_size_image], verbose_name='Обложка жанры')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Трек')),
                ('description', models.TextField(max_length=155, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, upload_to=basic_services.service.get_path_upload_track_cover, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), basic_services.service.validate_size_image], verbose_name='Обложка')),
                ('listening', models.PositiveIntegerField(default=0, verbose_name='Прослушивания')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Скачиваний')),
                ('private', models.BooleanField(default=False, verbose_name='Приватный')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_album', to='sound.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('genres', models.ManyToManyField(blank=True, related_name='track_genres', to='sound.genre', verbose_name='Жанры')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
            ],
        ),
    ]
