# Generated by Django 4.1.3 on 2022-11-12 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite_albums',
            field=models.ManyToManyField(related_name='alboms_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранные альбомы'),
        ),
        migrations.AddField(
            model_name='track',
            name='favorite',
            field=models.ManyToManyField(related_name='tracks_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Добавили в избранное'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks_album', to='sound.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks_genres', to='sound.genre', verbose_name='Жанры'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='likes',
        ),
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнули треки'),
            preserve_default=False,
        ),
    ]
