# Generated by Django 4.1.3 on 2022-11-14 12:52

import basic_services.service
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0002_album_favorite_albums_track_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_tracks', to='sound.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(upload_to=basic_services.service.get_path_upload_track_file, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Трек'),
        ),
    ]
