# Generated by Django 4.1.3 on 2022-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_remove_track_album_album_tracks_alter_track_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tracks',
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='album_tracks', to='sound.track'),
        ),
    ]
