# Generated by Django 4.1.3 on 2022-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0004_remove_album_tracks_album_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
