# Generated by Django 4.1.3 on 2022-11-15 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sound', '0005_album_slug_track_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, related_name='alboms_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранные альбомы'),
        ),
        migrations.AlterField(
            model_name='track',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='tracks_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Добавили в избранное'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='likes',
        ),
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tracks_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнули треки'),
        ),
    ]
