# Generated by Django 4.1.3 on 2022-11-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Инста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='twitter',
            field=models.URLField(default=1, verbose_name='Твитер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='youtube',
            field=models.URLField(default=1, verbose_name='Ютуб'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_sub', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
        ),
    ]
